"""add phone number

Revision ID: 37648b9247f9
Revises: ef14de31e6de
Create Date: 2022-09-08 19:56:39.089526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37648b9247f9'
down_revision = 'ef14de31e6de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
